[[feedback]]
= FEEDBACK

Hi Malaya-

The following is feedback on your example/test:

1. First, I https://github.com/jxblum/geode-client/commit/9bf434782f1cdcc9abc0873c88e07774495b7b09[refactored]
the Gradle build file to only contain the essential (dependency) declarations required to build and run
the Spring Boot application and test.

2. The `Customer` (application domain model/persistent entity) class is inappropriately https://github.com/nayakmk/geode-client/blob/main/src/main/java/com/example/geodeclient/regions/Customer.java#L8[annotated]
with SDG's https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/mapping/annotation/ReplicateRegion.html[`@ReplicateRegion`] "mapping" annotation.
`REPLICATE` Regions are only applicable to peer `Cache` applications, not clients, as your Spring Boot has been
https://github.com/nayakmk/geode-client/blob/main/src/main/java/com/example/geodeclient/GeodeClientApplication.java#L8-L10[declared].

3. Then, you inappropriately https://github.com/nayakmk/geode-client/blob/main/src/main/java/com/example/geodeclient/regions/GlobalRegionConfiguration.java#L14-L15[annotated]
your Spring `@Configuration` annotated `GlobalRegionConfiguration` class with SDG's https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/mapping/annotation/ClientRegion.html[`@ClientRegion`] "mapping" annotation.
The `@ClientRegion` "mapping" annotation, along with all SDG "mapping" annotations in
the https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/mapping/annotation/package-frame.html[o.s.data.gemfire.mapping] package,
for that matter, are only used to annotate application domain model/persistent entity classes with "mapping metadata",
which is used by the Spring Data [Geode] framework to store an objects in Regions. In general, a SD[G] "mapping" annotation
identifies the Region in which the entity (POJO) is persisted, much like JPA's `@Table` annotation "names" the database
table in which the entity is mapped and stored. Additionally, SDG's "mapping" annotations provide additional metadata
for creation of the Region on the Spring application-side only when additionally combined with SDG's `@EnableEntityDefinedRegions`
annotation. This mapping metadata from mapping annotations is not pushed to the servers for Region creation
when combined with SDG's `@EnableCluserConfiguration` annotation.

4. Therefore, and for some reason, you seem to think that https://github.com/nayakmk/geode-client/blob/main/src/main/java/com/example/geodeclient/regions/Customer.java#L8[annotating]
your `Customer` class with `@ReplicateRegion` combined with https://github.com/nayakmk/geode-client/blob/main/src/main/java/com/example/geodeclient/regions/GlobalRegionConfiguration.java#L14[annotating]
your configuration class with `@ClientRegion` and https://github.com/nayakmk/geode-client/blob/main/src/main/java/com/example/geodeclient/regions/GlobalRegionConfiguration.java#L12[declaring]
the `@EnableClusterConfiguration` annotation will somehow create a client-side Region "Customers", then push
the configuration of this client Region up to the servers in the cluster as a "GLOBAL", `REPLICATE` Region.
None of this is true.

5. https://github.com/nayakmk/geode-client/blob/main/src/main/java/com/example/geodeclient/regions/GlobalRegionConfiguration.java#L12[Declaring]
the https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/EnableClusterConfiguration.html[`@EnableClusterConfiguration`] annotation
without implicitly (using https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/EnableEntityDefinedRegions.html[`@EnableEntityDefinedRegions`])
or explicitly (using Java-based configuration, as you have https://github.com/nayakmk/geode-client/blob/main/src/main/java/com/example/geodeclient/regions/GlobalRegionConfiguration.java#L17-L24[commented out])
does nothing. You need a Region (bean) definition using `@EnableEntityDefinedRegions`, or with explicit Region bean definition
as you have defined/declared in Java-based configuration. SDG's `@EnableClusterConfiguration` feature uses the Regions
created in the cache (e.g. the `@ClientCache` instance, in your case) to determine which Regions to create on the servers.
If the cache has no created Regions, then there is nothing to "push".

> TIP: You should review the following: https://docs.spring.io/spring-data/geode/docs/current/reference/html/#mapping[POJO Mapping],
https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config-regions[Configuring Regions]
(refer to _Spring Boot for Apache Geode's_ ref doc and guidance for https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-configuration-declarative-annotations-productivity-regions[more concise information]
on the topic of "declarative" Region creation, and specifically for https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-configuration-declarative-annotations-productivity-regions-enableentitydefined[`@EnableEntityDefinedRegions`]),
https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config-cluster[Cluster Configuration Push]
(to get the real power of Spring Boot, you should use _Spring Boot for Apache Geode_ (SBDG's) and SBDG's
https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-configuration-declarative-annotations-productivity-enableclusteraware[`@EnableClusterAware`] annotation).

6. In conclusion, I https://github.com/jxblum/geode-client/tree/feedback[modified] your Spring Boot application to work as expected,
with the following results:

First, start an Apache Geode cluster using _Gfsh_:

[source,txt]
----
$ gfsh
    _________________________     __
   / _____/ ______/ ______/ /____/ /
  / /  __/ /___  /_____  / _____  /
 / /__/ / ____/  _____/ / /    / /
/______/_/      /______/_/    /_/    1.14.4

Monitor and Manage Apache Geode
gfsh>
gfsh>
gfsh>start locator --name=LocatorOne
Starting a Geode Locator in /Users/jblum/pivdev/lab/LocatorOne...
........
Locator in /Users/jblum/pivdev/lab/LocatorOne on 10.99.199.19[10334] as LocatorOne is currently online.
Process ID: 20273
Uptime: 10 seconds
Geode Version: 1.14.4
Java Version: 1.8.0_351
Log File: /Users/jblum/pivdev/lab/LocatorOne/LocatorOne.log
JVM Arguments: -Dgemfire.enable-cluster-configuration=true -Dgemfire.load-cluster-configuration-from-dir=false -Dgemfire.launcher.registerSignalHandlers=true -Djava.awt.headless=true -Dsun.rmi.dgc.server.gcInterval=9223372036854775806
Class-Path: /Users/jblum/pivdev/apache-geode-1.14.4/lib/geode-core-1.14.4.jar:/Users/jblum/pivdev/apache-geode-1.14.4/lib/geode-dependencies.jar

Successfully connected to: JMX Manager [host=10.99.199.19, port=1099]

Cluster configuration service is up and running.


gfsh>start server --name=ServerOne
Starting a Geode Server in /Users/jblum/pivdev/lab/ServerOne...
...
Server in /Users/jblum/pivdev/lab/ServerOne on 10.99.199.19[40404] as ServerOne is currently online.
Process ID: 20401
Uptime: 2 seconds
Geode Version: 1.14.4
Java Version: 1.8.0_351
Log File: /Users/jblum/pivdev/lab/ServerOne/ServerOne.log
JVM Arguments: -Dgemfire.default.locators=10.99.199.19[10334] -Dgemfire.start-dev-rest-api=false -Dgemfire.use-cluster-configuration=true -XX:OnOutOfMemoryError=kill -KILL %p -Dgemfire.launcher.registerSignalHandlers=true -Djava.awt.headless=true -Dsun.rmi.dgc.server.gcInterval=9223372036854775806
Class-Path: /Users/jblum/pivdev/apache-geode-1.14.4/lib/geode-core-1.14.4.jar:/Users/jblum/pivdev/apache-geode-1.14.4/lib/geode-dependencies.jar


gfsh>list members
Member Count : 2

   Name    | Id
---------- | ------------------------------------------------------------------
LocatorOne | 10.99.199.19(LocatorOne:20273:locator)<ec><v0>:41000 [Coordinator]
ServerOne  | 10.99.199.19(ServerOne:20401)<v1>:41001


gfsh>list regions
No Regions Found

gfsh>

----

Then, run the application; you should see:

[source,txt]
----
gfsh>list regions
List of regions
---------------
Customers


gfsh>describe region --name=/Customers
Name            : Customers
Data Policy     : replicate
Hosting Members : ServerOne

Non-Default Attributes Shared By Hosting Members

 Type  |    Name     | Value
------ | ----------- | ---------------
Region | data-policy | REPLICATE
       | size        | 1
       | scope       | distributed-ack


gfsh>query --query="SELECT c.name FROM /Customers c"
Result : true
Limit  : 100
Rows   : 1

Result
-------
Jon Doe


gfsh>
----
